image: Visual Studio 2017
platform: Any CPU

environment:
  version: $(APPVEYOR_BUILD_VERSION)

configuration:
- Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '%version%'
  package_version: '%version%'
  assembly_version: '%version%'
  file_version: '%version%'
  informational_version: '%version%'

build:
  project: RestSharp.Serilog.Auto.sln

after_test:
  - dotnet pack --configuration Release /p:Version=%version%

artifacts:
  - path: RestSharp.Serilog.Auto\bin\Release\netstandard2.1\RestSharp.Serilog.Auto.dll
    name: RestSharp.Serilog.Auto.dll
  - path: RestSharp.Serilog.Auto\bin\Release\RestSharp.Serilog.Auto.%version%.nupkg
    name: RestSharp.Serilog.Auto.%version%.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: hb5jOmzsvUKCtOP41EFtc/lwXAOh5auC5KAi2Ok9i/FmTuo2F36yzEgaPiT9olsB